<<<<<<< HEAD
title:            Dominic Tristram
description:      Social and Environmental Campaigner in Bath
logo:             site-logo.png
disqus_shortname: dominictristram
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://dominictristram.com

# Owner/author information
owner:
  name:           Dominic Tristram
  avatar:         bio-photo.jpg
  email:          dominic@dominictristram.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        DominicTristram
  facebook:       DomTristram
  github:         dominictristram
  stackexchange:  
  linkedin:       dominictristram
  instagram:      dominicuk
  flickr:         dominic_tristram
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+DominicTristram

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-22078476-1
google_verify:      FF8DVyVv5h7AQiS7OHpfd4fsnGyGravPDWiBM3DSASo
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /index.html
  - title: About Me
    url: /about.html
  - title: Articles
    url: /articles/
  - title: Media
    url: /media/
  - title: Events
    url: /events/
  - title: General Election
    url: /bath2015/
  - title: Hospital Governor
    url: /ruhgovernor.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title/
permalink:   /:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor"]
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
# remote_theme: mmistakes/so-simple-theme
remote_theme: daattali/beautiful-jekyll@5.0.0
skin: "/assets/css/skins/default.css"
locale: en-US
title: "My Awesome Site"
description: "It really is the best."
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
>>>>>>> 7c881becad9ced654320a46c464a2fe77b093622
