---
layout: post
title: Government Document Admits to NHS Privatisation
---

h1. {{ page.title }}

<img src="http://www.dominictristram.com/images/NHS-logo.jpg">

p(meta). 24 November 2011

The Department of Health has recently published some draft guidelines outlining support for CCG's called <a href="http://www.hsj.co.uk/Journals/2011/11/09/t/q/p/Towards-Service-Excellence_021111-FINAL.pdf">Developing Commissioning Support: Towards Service Excellence</a>. This report makes interesting, and rather worrying, reading. In summary this document is a direct statement of NHS privatisation and how it will happen. But you don't have to take my word for it - let's look at the document.

First one must get through the obvious pro-reform fluff and nonsense in the language used. The longer one works within government the more one realises that far from being neutral, evidence-based documents, reports such as this are basically party political propaganda dressed as fact. You can see this within the first few paragraphs of the first chapter - there's plenty of talk of aspirations to make the NHS deliver "health outcomes among the best in the world" and how the new Clinical Commissioning Groups will help the NHS improve "best value for money". All noble aims? Perhaps, but what it doesn't mention is the fact that the NHS already provides these things.

The Organisation for Economic Co-operation and Development (OECD) recently published its regular <a href="http://www.oecd-ilibrary.org/social-issues-migration-health/health-at-a-glance-2011_health_glance-2011-en">Health at a Glance</a> report comparing healthcare in major economies. It shows that the NHS is performing exceptionally well with comparable statistics to the rest of Europe for life expectancy, but with less paid per capita than almost all other healthcare systems. These findings are in line with November's <a href="http://www.commonwealthfund.org/Publications/In-the-Literature/2011/Nov/2011-International-Survey-Of-Patients.aspx">Commonwealth Fund survey</a>, which showed the NHS as one of the best healthcare systems in the world, the one that performed best of all on the co-ordination of care for patients, patient safety, and the way in which patients are engaged in their care.

So by all independent, international comparisons the NHS is doing very well. What does the government think its ideological shoehorning-in of the private sector, with no basis in evidence, will achieve? Perhaps someone charitable might think that even if it doesn't help, it can't really hurt? Think again. Mark Pearson, head of health at the OECD, <a href="http://www.guardian.co.uk/politics/2011/nov/23/health-bill-nhs-oecd-report">told The Guardian</a> "The UK is one of the best performers in the world. But outcomes are not what you expect because there is a big reform every five years. We calculate that each reform costs two years of improvements in quality. No country reforms its health service as frequently as the UK ... But there's no big reform that will improve it. Better to let it bed down and tinker rather than wondering about more or less competition. It is less the type of system that counts, but rather how it is managed."

With the lack of any evidence that changes to the NHS will make it better, the only logical conclusion is that the changes are ideological. The government strenuously denies that it's all about privatisation and favours to donors, but it obviously is. There's the <a href="http://www.dominictristram.com/2011/11/15/circle-nhs-takeover.html">Circle takeover of Hinchingbrooke</a> that I mentioned previously, where a hospital is being given to Circle Healthcare, a tax-haven based company run by Tory donors, and then there's yet more evidence in these guidelines just published. Dr Jonathan Tomlinson, an east London GP and blogger, <a href="http://www.channel4.com/news/proof-government-plans-to-privatise-nhs">told Channel 4 News:</a> "The document says that GPs who are wanting to design services from their patients will have to get support from private companies. However that support is so comprehensive as to include absolutely everything that commissioning involves ... In other words, looking at the needs of their local population, choosing and designing the services that they need, managing the contracts, monitoring the quality. There's almost nothing left for us to do. And it even goes so far as saying that they can see a role for GPs perhaps in managing learning difficulties or other small local community services but even then private companies will be doing the directing."

A Department of Health spokesman told Channel 4 News that it was wrong to claim the NHS was to be privatised and that document was quite simply about back office functions. But again, as with Circle, what is privatisation if it's not taking something currently run by the State as a service (commissioning) and handing it to the private sector to run at a profit?

The government attempted to sell the changes to the NHS as a way to hand control of commissioning to GPs and 'family doctors'. That didn't really make sense (GPs are not necessarily good at management), but it was at least an attempt to explain the changes as something other than the outright privatisation that they actually are. Now, with GPs realising that they will effectively have no control with <a href="http://www.inpharm.com/news/170062/private-sector-role-nhs-commissioning-opposed">large multinational consultancies such as KPMG running commissioning</a>, the truth has started to hit home.

Responding to the OECD report, Health Secretary Andrew Lansley said ""Improving patient results is a top priority for me. We need to allow the NHS to focus on what really matters to patients; things like survival rates, recovery rates and whether people can live independently and with dignity.", conveniently ignoring the fact that the OECD thinks the changes will make healthcare worse and cost billions. He knows this, of course, but improving the NHS isn't really his objective - it's the carving-up of it into chunks that can be sold. It has started with 'back-office functions'. It won't stop there.
